### ISSUE TITLE
Improve table CSS

### ISSUE THREAD

**Issue by mattico** [rust-lang/blog.rust-lang.org#154]
The lack of lines or spacing can make tables hard to read.

![image](https://cloud.githubusercontent.com/assets/853158/24010655/84d39740-0a46-11e7-8c00-d36fc5394d29.png)

**Comment by steveklabnik** [comment]
Would love a PR for this.

**Comment by distransient** [comment]
I could pick this up this afternoon if nobody else wants to do it

**Comment by mattico** [comment]
@distransient I was just going to say the same thing. Go for it!

**Comment by mattico** [comment]
Inspiration: https://www.reddit.com/r/rust/comments/5zrzkf/announcing_rust_116/df0sv08/

**Comment by lqd** [comment]
In case anyone needs it, here's what I did for this last-linked example (besides presenting the data in a column :) 

- `text-align: right` the td/th cells which are `:not(:first-child)`
- on those same cells, added a substantial right padding
- added a slight left padding on the `td:first-child` (which should probably be played with a bit more tbh)

I'm not sure at which level you can control the markdown-generated HTML to have one row with a CSS class but:
- the "separator row"'s td have a bottom padding, as well as a border-bottom (around 50% grey, like #888)
- the "row following the separator row"'s td (à la `tr.separator + tr td`) have the same amount of top padding as the previous row's bottom padding
- since this is a border separator rather than a thinner empty row (which might be pulled off with markdown ?), the table had to be `border-collapse`d as well
