### ISSUE TITLE
Add code highlighting to code in blog posts

### ISSUE THREAD

**Issue by toothbrush7777777** [rust-lang/blog.rust-lang.org#342]
Just a suggestion. I think the old blog had that?

**Comment by danilaml** [comment]
It's baffling it's not a priority. For an official programming language blog that is. Until it's fixed the redesign remains a significant downgrade from the previous iteration.

**Comment by steveklabnik** [comment]
Things take time. Everyone agrees this is important; there are just bigger things at play here.

**Comment by danilaml** [comment]
@steveklabnik true, but I don't see any activity on these issues since December. At this point, I don't see any value of a design switch, at least for Blog. Especially since there seems to be no way to switch back for a user. This just gives this redesign a "rushed" feel (I remember blog being particularly unusable in the first weeks after the switch, like it was just an afterthought, though now highlighting is the only major feature missing), which is certainly no the best "front" for the language itself.

**Comment by steveklabnik** [comment]
Sure. December was not that long ago. The first week was the edition release, and then all of the holidays, and then prep for the all hands... there’s a *lot* to do in the rust project.

Not every bit of work is translated into an issue.

**Comment by danilaml** [comment]
Welp, almost a year later and nothing's changed. It's annoying to be reminded about it every time I read about the next exciting Rust update =(
