### ISSUE TITLE
Are section headers supposed to be `inline-block`?

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/blog.rust-lang.org#453]
Most other blog templates I've used don't have this style so I was a bit confused to see that

```markdown
## Working group sync 

### [wg-polonius](link)
```

renders on one line

![image](https://user-images.githubusercontent.com/831192/68610852-c37b7c00-0486-11ea-83da-5eb47bc0efc2.png)

If this is intended behavior, feel free to close this issue. I tried looking at other published blog posts and couldn't find any that triggered this (or were relying on the `inline-block` behavior).

**Comment by Zexbe** [comment]
It renders on two lines for me
![render](https://user-images.githubusercontent.com/12435876/73129276-8f4b2e00-3f94-11ea-80dd-c5201f9c533b.png)

**Comment by wesleywiser** [comment]
@Zexbe I "fixed" the issues by manually inserting `<br />` tags in https://github.com/rust-lang/blog.rust-lang.org/commit/5a4b152d07acbf922868f1e5889fc7c8af4df3b9

**Comment by Zexbe** [comment]
@wesleywiser I could not find any posts, or part of the site that depend on the behavior.
The only non-markdown thing that is using a h3 is the header for each year section. When I set it to block, it looks exactly the same at multiple different device sizes. 
I looked at all the blogs (using regex). I found no blog posts depending on this behavior, and found one that had an issue because of it, 2018-08-02-Rust-1.28.md

I looked at two other websites to see if they had this behavior: mdbook, and hackmd. They do not have this behavior.

I think we should remove the inline-block, and the <br /> tags you had to insert because of the bug.

**Comment by wesleywiser** [comment]
@Zexbe that seems entirely reasonable to me but I know very little about how the site is structured or designed so I didn't want to presume that removing "inline-block" was the correct thing to do.

If you've found that we're definitely not relying on it, then I think a patch to remove it and the `<br />` tags I added seems valid to me.
