### ISSUE TITLE
Rust Unstable Book link is broken

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang/blog.rust-lang.org#524]
https://github.com/rust-lang/blog.rust-lang.org/blob/990972d6610a211777664a5c65269f550ff0c46f/posts/inside-rust/2020-02-25-intro-rustc-self-profile.md has a link [documentation for this feature](https://doc.rust-lang.org/unstable-book/compiler-flags/self-profile.html) (https://doc.rust-lang.org/unstable-book/compiler-flags/self-profile.html) that is broken. I was unable to find what the correct link should be.

**Comment by XAMPPRocky** [comment]
cc @wesleywiser

**Comment by wesleywiser** [comment]
The links should go live the next time the Rust Unstable Book is deployed which I thought would happen nightly. Perhaps it's on a different schedule than that?

**Comment by ehuss** [comment]
The nightly docs are auto-published each night with the https://doc.rust-lang.org/nightly/ url. Each release channel has a separate top-level directory (stable, beta, nightly, 1.xx.y, etc.), with the root directories being aliases for `/stable/…`.  So that URL would be https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/self-profile.html.

**Comment by wesleywiser** [comment]
Ah, that makes sense. Thank you!
